- src/stories/CardContainer.stories.tsx
- src/stories/Image.stories.tsx
- src/stories/Input.stories.tsx
- src/stories/Modal.stories.tsx
이전에 Storybook을 만들 때 디렉토리 구조에 대한 컨벤션을 정했었는데요. 컴포넌트의 경우 atoms, domains, templates로 디렉토리를 따로 세부적으로 추가해서, 구현하기로 협의하였습니다.
현재의 경우 이러한 컨벤션을 제대로 지켜지지 않은 상태여서, 이를 통일하겠습니다.
> [TLVB-30] 스토리북 디렉토리 구조 변경

- .eslintrc.js
- src/components/atoms/HeaderText.tsx
- src/stories/HeaderText.stories.tsx
1. `Header` 컴포넌트와 혼동할 우려가 있어 `HeaderText`로 명명하였습니다.
2. `Dynamic Tags`을 적용하였습니다.
3. `Dynamic Tags`에 따른 세부 `Emotion CSS-in-JS Styling`이 가능하도록 구현하였습니다.
정상적으로 다이나믹하게 태그 엘리먼트 및 스타일링 변화가 적용됨을 좌측 검사 창 및 오른쪽 테스트 동작에서 확인 가능합니다.
[Jira - 배경 및 필요성](https://6th-dev-course.atlassian.net/jira/software/projects/TLVB/boards/1?selectedIssue=TLVB-31)
[TWL - React Dynamic Tag with TypeScript](https://oranjik.notion.site/React-Dynamic-Tag-with-TypeScript-de81ee8d7729481ba2db70b7fdcecd76)
[TWL - JSX is not defined](https://oranjik.notion.site/JSX-is-not-defined-6c2bcd61519e4c88922bf90cc81b59e9)
> [TLVB-31] HeaderText 구현

- .stylelintrc.js
- src/components/atoms/CardContainer.tsx
- src/components/atoms/CardList.tsx
- src/stories/CategoryList.stories.tsx
CardContainer을 구현하기 위해 필요한 atoms 컴포넌트입니다.
CardItem들을 담는 역할을 수행하며, CardItem이 article이므로 ul이 아닌 section으로 구현하였습니다.
따라서,  flex가 row인 경우, default이며, 만약 none으로 한다면, block으로 설정됩니다.
이는 Context Margin 병합이 flex인지, block인지에 따라 다르기에 다음과 같이 설정했습니다.
아직 margin에 따른 세부 설정은 제대로 구현하지 않았으나, 이를 통해 특정 height만큼만 보여줄 수 있도록 overflow 및 height 설정이 가능합니다.
예를 들어, 만약 10개의 `item`을 만들고, `overflowHeight`를 하나만 보여줄 수 있도록 설정한다면 다음과 같습니다.
1. 인덱스 시그니처를 직접 사용해 본 결과, 타입 설정에 있어 매우 간편함을 느낄 수 있었습니다!
2. 스토리북 v7에서는 `defaultValue`를 사용하지 않는다는 것을 `deprecated warning console` 및 [공식 문서](https://storybook.js.org/docs/react/essentials/controls)를 통해 확인하였습니다. 추후 리팩토링할 예정입니다.
3. `prop`으로 값을 넘겨줄 때 다음과 같이 타입 단언을 사용하면 좀 더 편하게 타입 추론을 제공할 수 있습니다.
```jsx
<CardList {...args}>
{arr.map((_, idx) => (
<CardContainer
key={_}
cardType="default" …
```
> [TLVB-32] CardList 구현

- package-lock.json
- postcss.config.js
- src/components/atoms/Button.tsx
- src/stories/Button.stories.tsx
- src/styles/index.js
- index.js global style에 confirm 컬러 추가
- Button component 추가
* buttonType을 통해 default(primary), warning, confirm을 설정할 수 있으며
재사용성이 높을 것 같아 일단 type별로 따로 만들어 놓았습니다. (추후 논의)
* button size는 따로 지정된 게 없어 일단 auto로 지정해놓았습니다. (추후 논의)
* background color는 미리 지정한 색상이 따로 있기 때문에 변경되지 않습니다.
* 정렬을 flex 또는 padding으로 한다는 의견을 반영하여 둘 다 추가하였습니다.
* 버튼의 경우 기존 버튼에서 텍스트와 배경 색상만 바뀌는 버튼도 있어 reversal속성을 추가하였습니다.
> [TLVB-14] 버튼 컴포넌트 구현

- src/components/atoms/Button.tsx
- src/components/domains/CategoryList.tsx
- src/stories/Button.stories.tsx
* 버튼 컴포넌트 수정
* domains/CategoryList 추가 수정 -> 나중에 수정바람
* [관련 PR](https://github.com/prgrms-web-devcourse/Team_Everevent_Kazedon_FE/pull/20) 
* reversal 선택여부에 따라 border도 넣을지 안 넣을지 여부를 설정할 수 있습니다.
* 필요할 때마다 버튼 컴포넌트에 대한 의견 주세요!
> [TLVB-43] 버튼 컴포넌트 수정

- src/components/domains/NavModal/Modal.tsx
- src/components/domains/NavModal/Navigator.tsx
- src/components/domains/NavModal/index.ts
- src/stories/NavModal.stories.tsx
NavModal구현했으나
사용자(user)와 사업자(owner) 나눠서 구현했습니다.
링크 부분은 따로 추가하시면 됩니다.
> [TLVB-18] NavModal구현 

- src/components/atoms/Button.tsx
- src/components/domains/SortButtons.tsx
- src/stories/SortButtons.stories.tsx
리스트를 정렬하는 버튼들을 모아놓는 컴포넌트를 구현합니다.
> [TLVB-45] SortButtons 컴포넌트 구현

- src/components/atoms/Input.tsx
> [TLVB-50] Input 컴포넌트 develop

- fixtures/events.ts
전체 이벤트 조회를 실시하는 API를 생성합니다.
Test API의 경우 `fixtures` 브랜치에서 생성해주시면 될 거 같습니다!
> [TLVB-55] 전체 이벤트 조회 API 테스트용 데이터 생성

- src/components/atoms/Input.tsx
onChange를 Props로 받지 못하는 부분을 수정했습니다.
> [TLVB-60] Input onChange 추가

- src/components/domains/RegisterForm.tsx
- src/stories/LoginForm.stories.tsx
- src/stories/RegisterForm.stories.tsx
> [TLVB-56] 회원가입 레이아웃 구성

- src/components/atoms/Button.tsx
* 버튼 컴포넌트 ButtonProps에 onClick을 추가하였습니다.
> [TLVB-61] 버튼 onClick 추가

- src/components/domains/LoginForm.tsx
아이디 비밀번호입력후 console.log확인하시면 됩니다!
> [TLVB-59] 로그인 폼 UseForm연결

- src/components/domains/LoginForm.tsx
- src/hooks/useForm.ts
- src/pages/login/index.tsx
> [TLVB-63] 로그인 폼 페이지 설정

- next-env.d.ts
- src/components/atoms/CardContainer.tsx
- src/components/domains/Header.tsx
- src/components/domains/SortButtons.tsx
- src/pages/index.tsx
- src/stories/CardList.stories.tsx
- src/stories/CategoryList.stories.tsx
- src/stories/SortButtons.stories.tsx
1. 헤더 적용
2. 전반적인 메인 페이지 레이아웃 생성
3. 테스트 데이터 적용
1. CardContainer 내부 컴포넌트 스타일 미구현
2. API 미생성
> [TLVB-52] Main Page 레이아웃 생셩 및 테스트 데이터 적용

- .gitignore
- firebase.json
- next-env.d.ts
- package.json
파이어베이스에 배포하기 위한 최종 작업을 실시합니다.
현재는 release브랜치가 존재하지 않는 것 같아, 디벨롭 브랜치에서 이를 먼저 완성시킨 후 마스터에 머지하는 방향으로 전개하면 될 것 같습니다.
성공적으로 빌드 및 배포를 완료하였습니다.
라우팅 기능도 정상적으로 동작합니다  
https://everevent-be69d.web.app/
> [TLVB-64] 파이어베이스 배포 세팅

- .babelrc
- .storybook/main.js
- src/contexts/index.tsx
- tsconfig.json
contexts 디렉토리의 절대 경로가 누락되어 있어 이를 추가합니다.
> [TLVB-67] contexts 절대경로 추가

- src/components/domains/RegisterForm.tsx
- src/pages/register/index.tsx
* 회원가입 폼에 useForm hook을 추가
* /register로 회원가입 페이지 확인가능
* validation 미구현
* 회원가입 후 회원가입 완료 페이지로 이동해야함
-> 현재 회원가입 버튼 클릭 시 입력 데이터를 console로 보여줍니다.
> [TLVB-62] 회원가입 폼 useForm연결

- next-env.d.ts
- src/components/domains/EventCard.tsx
- src/pages/index.tsx
- src/stories/EventCard.stories.tsx
- **구현 사항**
1. 이벤트를 조회할 수 있는 카드인 `EventCard`를 구현하였습니다.
2. 스토리북을 통해 테스트가 가능합니다.
3. props는 다음과 같습니다.
- `eventData`: 이벤트 카드에 필요한 데이터입니다. (`fixtures/events` 참고)
- `idx` 카드의 인덱스(색상 지정)입니다. 
- `width` 카드의 너비 지정입니다. (기본: `auto`)
- 
- **미구현 사항**
1. `react-icons`를 적용하지 않았습니다.
2. `LikeButton`, `ReviewCount` 에 대해 별도로 컴포넌트 분리가 이루어지지 않았습니다. (추후 필요 시 리팩토링 예정)
> [TLVB-68] EventCard 구현, storybook 테스트 적용

- src/components/atoms/Input.tsx
- src/components/domains/LoginForm.tsx
- src/hooks/useForm.ts
1. 아이디 비밀번호 없을 때 검증
2. 아이디가 이메일 형식이 아닐 때
3. 비밀번호가 없을 때
4. 아이디가 없을 때
총 4가지 경우에 대해 Validation을 적용했습니다. 누락되거나 부족한 부분있다면 리뷰를 달아주세요!
> [TLVB-70] 로그인폼 develop

- fixtures/event.ts
- fixtures/favorites.ts
- fixtures/likeEvents.ts
- fixtures/login.ts
- fixtures/myReviews.ts
- fixtures/participatedEvents.ts
- fixtures/reviewerInfo.ts
- fixtures/reviews.ts
- fixtures/shop.ts
- fixtures/shopEvents.ts
- fixtures/userInfo.ts
[API 명세서](https://www.notion.so/oranjik/API-62562bdc6ffc4015963fde37a6e4f620)에 있는 내용 그대로 테스트 데이터를 작성하였습니다.
- 일단 석연치 않는 부분이 있다면, 내일 회의 때 API 데이터 변경할 부분들을 가져오면 좋을 것 같아요! 
- 혹시나 위의 URL과 다르게 적혀있는 부분이 있다면 말씀해주시면 감사하겠습니다 :)
이벤트 정보 수정(API-22)는 아직 모호하여 추가하지 않았습니다.
또한, 아직 이벤트 세부 타입(하위 프로퍼티 string, number 등의 타입)은 미정이니, 이런 세세한 타입은 일단 모두 string으로 default를 설정했습니다.
> [TLVB-72] UI component 동작 test를 위한 임시 dataset 추가

- src/components/domains/UserChangeForm.tsx
- src/stories/UserChangeForm.stories.tsx
* 사업자 전환 페이지 레이아웃 구성
* 각 input, textarea에 해당하는 값에 대한 validation 기능 추가할 예정입니다. 
* Header가 추가될 예정입니다.
* UserChangeForm이라고 네이밍하였는데 더 좋은 네이밍이 있으면 추천해주세요,, 😂
> [TLVB-76] 가게보기(사업자 등록) 페이지 레이아웃 구성

- .babelrc
- .storybook/main.js
- src/components/atoms/index.ts
- src/components/domains/index.ts
- tsconfig.json
export 파일 만들었으니 domains 리팩토링 바랍니다!
상수는 @utils/~~~ 로 불러서 사용하시면 됩니다!
> [TLVB-84] 컴포넌트 단위 index.ts로 export 하기 및 상수 폴더 선언

- src/axios/event/getEvent.ts
- src/axios/event/getEventList.ts
- src/axios/index.ts
- src/axios/types.ts
- src/components/domains/LoginForm.tsx
- src/components/domains/RegisterForm.tsx
- src/contexts/eventList/actions.tsx
- src/contexts/eventList/index.tsx
- src/contexts/eventList/types.ts
- src/contexts/types.ts
- src/stories/domains/EventCard.stories.tsx
Axios interceptor을 효과적으로 사용할 수 있또록 전역 상태 및 API를 리팩토링한다.
1. API를 사용할 때, `res.data`로 반환을 했기 때문에, 에러가 났을 경우는 제대로 파악하지 못한다.
2. 이후 백엔드에서 만약 API 에러에 대한 메세지를 처리해준다면, 이는 확장성이 낮아질 우려가 있다.
1. interceptor에서 어떠한 처리든 일관적인 응답을 할 수 있도록 구현했다.
2. 이에 따라, 기존 전역 상태 관리 로직 역시 일관된 로직 처리가 가능하도록 수정했다.
항상 응답은 다음과 같은 구조로 반환된다.
1. data: 기본 데이터를 받는다.
2. headers: 응답 헤더를 받는다. (이는 유저 토큰을 받기 위함)
3. error: 에러 시 상태 코드 (설사 백엔드에서 처리하지 않더라도 우리가 코드 내에서 처리하기 위함), 에러 메세지를 받는다.
> [TLVB-93] Axios interceptor에 따른 전역 상태 및 API 리팩토링

- src/components/domains/Header.tsx
- src/components/domains/LoginForm.tsx
- src/pages/login/index.tsx
헤더 DefaultProps를 추가하여 변경했습니다! 확인부탁드릴게요!
> [TLVB-105]  로그인 페이지 구현

- src/axios/user.ts
- src/components/domains/LoginForm.tsx
- src/components/domains/RegisterForm.tsx
- src/contexts/UserContext/actions.ts
- src/contexts/UserContext/index.tsx
- src/contexts/UserContext/reducer.ts
- src/contexts/UserContext/types.ts
- src/hooks/useForm.ts
- src/pages/register/index.tsx
- src/utils/constantUser.ts
검증 부분이 상당히 많아 케이스가 많아서 다 못잡았습니다. 앞으로 차차 develop할 예정이며 피드백 적극 반영합니다!
작업을 상세히 쪼개지 못해 리뷰가 힘들거 같습니다. 죄송합니다ㅠㅠ
> [TLVB-106] 회원가입페이지 만들기
